"""add name to the user

Revision ID: 2038a62eee57
Revises: 584f8e5c491d
Create Date: 2025-11-23 14:49:20.184207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2038a62eee57'
down_revision: Union[str, Sequence[str], None] = '584f8e5c491d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'consumer_staff', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'incident_logs', 'incidents', ['incident_id'], ['id'])
    op.create_foreign_key(None, 'platform_admins', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'product_images', 'products', ['product_id'], ['id'])
    op.add_column('users', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    op.drop_constraint(None, 'product_images', type_='foreignkey')
    op.drop_constraint(None, 'platform_admins', type_='foreignkey')
    op.drop_constraint(None, 'incident_logs', type_='foreignkey')
    op.drop_constraint(None, 'consumer_staff', type_='foreignkey')
    # ### end Alembic commands ###
