/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as DashboardSuppliersIndexRouteImport } from './routes/dashboard/suppliers/index'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as DashboardOrdersIndexRouteImport } from './routes/dashboard/orders/index'
import { Route as DashboardLinksIndexRouteImport } from './routes/dashboard/links/index'
import { Route as DashboardComplaintsIndexRouteImport } from './routes/dashboard/complaints/index'
import { Route as DashboardChatIndexRouteImport } from './routes/dashboard/chat/index'
import { Route as DashboardCatalogIndexRouteImport } from './routes/dashboard/catalog/index'
import { Route as AuthSupplierSignupIndexRouteImport } from './routes/auth/supplier/signup/index'
import { Route as AuthSupplierLoginIndexRouteImport } from './routes/auth/supplier/login/index'
import { Route as AuthConsumerSignupIndexRouteImport } from './routes/auth/consumer/signup/index'
import { Route as AuthConsumerLoginIndexRouteImport } from './routes/auth/consumer/login/index'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSuppliersIndexRoute = DashboardSuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardOrdersIndexRoute = DashboardOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardLinksIndexRoute = DashboardLinksIndexRouteImport.update({
  id: '/links/',
  path: '/links/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardComplaintsIndexRoute =
  DashboardComplaintsIndexRouteImport.update({
    id: '/complaints/',
    path: '/complaints/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardChatIndexRoute = DashboardChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCatalogIndexRoute = DashboardCatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthSupplierSignupIndexRoute = AuthSupplierSignupIndexRouteImport.update({
  id: '/auth/supplier/signup/',
  path: '/auth/supplier/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSupplierLoginIndexRoute = AuthSupplierLoginIndexRouteImport.update({
  id: '/auth/supplier/login/',
  path: '/auth/supplier/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConsumerSignupIndexRoute = AuthConsumerSignupIndexRouteImport.update({
  id: '/auth/consumer/signup/',
  path: '/auth/consumer/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConsumerLoginIndexRoute = AuthConsumerLoginIndexRouteImport.update({
  id: '/auth/consumer/login/',
  path: '/auth/consumer/login/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/auth': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/catalog': typeof DashboardCatalogIndexRoute
  '/dashboard/chat': typeof DashboardChatIndexRoute
  '/dashboard/complaints': typeof DashboardComplaintsIndexRoute
  '/dashboard/links': typeof DashboardLinksIndexRoute
  '/dashboard/orders': typeof DashboardOrdersIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/suppliers': typeof DashboardSuppliersIndexRoute
  '/auth/consumer/login': typeof AuthConsumerLoginIndexRoute
  '/auth/consumer/signup': typeof AuthConsumerSignupIndexRoute
  '/auth/supplier/login': typeof AuthSupplierLoginIndexRoute
  '/auth/supplier/signup': typeof AuthSupplierSignupIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/catalog': typeof DashboardCatalogIndexRoute
  '/dashboard/chat': typeof DashboardChatIndexRoute
  '/dashboard/complaints': typeof DashboardComplaintsIndexRoute
  '/dashboard/links': typeof DashboardLinksIndexRoute
  '/dashboard/orders': typeof DashboardOrdersIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/suppliers': typeof DashboardSuppliersIndexRoute
  '/auth/consumer/login': typeof AuthConsumerLoginIndexRoute
  '/auth/consumer/signup': typeof AuthConsumerSignupIndexRoute
  '/auth/supplier/login': typeof AuthSupplierLoginIndexRoute
  '/auth/supplier/signup': typeof AuthSupplierSignupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/catalog/': typeof DashboardCatalogIndexRoute
  '/dashboard/chat/': typeof DashboardChatIndexRoute
  '/dashboard/complaints/': typeof DashboardComplaintsIndexRoute
  '/dashboard/links/': typeof DashboardLinksIndexRoute
  '/dashboard/orders/': typeof DashboardOrdersIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/suppliers/': typeof DashboardSuppliersIndexRoute
  '/auth/consumer/login/': typeof AuthConsumerLoginIndexRoute
  '/auth/consumer/signup/': typeof AuthConsumerSignupIndexRoute
  '/auth/supplier/login/': typeof AuthSupplierLoginIndexRoute
  '/auth/supplier/signup/': typeof AuthSupplierSignupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/auth'
    | '/dashboard/'
    | '/dashboard/catalog'
    | '/dashboard/chat'
    | '/dashboard/complaints'
    | '/dashboard/links'
    | '/dashboard/orders'
    | '/dashboard/settings'
    | '/dashboard/suppliers'
    | '/auth/consumer/login'
    | '/auth/consumer/signup'
    | '/auth/supplier/login'
    | '/auth/supplier/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/catalog'
    | '/dashboard/chat'
    | '/dashboard/complaints'
    | '/dashboard/links'
    | '/dashboard/orders'
    | '/dashboard/settings'
    | '/dashboard/suppliers'
    | '/auth/consumer/login'
    | '/auth/consumer/signup'
    | '/auth/supplier/login'
    | '/auth/supplier/signup'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/auth/'
    | '/dashboard/'
    | '/dashboard/catalog/'
    | '/dashboard/chat/'
    | '/dashboard/complaints/'
    | '/dashboard/links/'
    | '/dashboard/orders/'
    | '/dashboard/settings/'
    | '/dashboard/suppliers/'
    | '/auth/consumer/login/'
    | '/auth/consumer/signup/'
    | '/auth/supplier/login/'
    | '/auth/supplier/signup/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
  AuthConsumerLoginIndexRoute: typeof AuthConsumerLoginIndexRoute
  AuthConsumerSignupIndexRoute: typeof AuthConsumerSignupIndexRoute
  AuthSupplierLoginIndexRoute: typeof AuthSupplierLoginIndexRoute
  AuthSupplierSignupIndexRoute: typeof AuthSupplierSignupIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/suppliers/': {
      id: '/dashboard/suppliers/'
      path: '/suppliers'
      fullPath: '/dashboard/suppliers'
      preLoaderRoute: typeof DashboardSuppliersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/orders/': {
      id: '/dashboard/orders/'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/links/': {
      id: '/dashboard/links/'
      path: '/links'
      fullPath: '/dashboard/links'
      preLoaderRoute: typeof DashboardLinksIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/complaints/': {
      id: '/dashboard/complaints/'
      path: '/complaints'
      fullPath: '/dashboard/complaints'
      preLoaderRoute: typeof DashboardComplaintsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/chat/': {
      id: '/dashboard/chat/'
      path: '/chat'
      fullPath: '/dashboard/chat'
      preLoaderRoute: typeof DashboardChatIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/catalog/': {
      id: '/dashboard/catalog/'
      path: '/catalog'
      fullPath: '/dashboard/catalog'
      preLoaderRoute: typeof DashboardCatalogIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/supplier/signup/': {
      id: '/auth/supplier/signup/'
      path: '/auth/supplier/signup'
      fullPath: '/auth/supplier/signup'
      preLoaderRoute: typeof AuthSupplierSignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/supplier/login/': {
      id: '/auth/supplier/login/'
      path: '/auth/supplier/login'
      fullPath: '/auth/supplier/login'
      preLoaderRoute: typeof AuthSupplierLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/consumer/signup/': {
      id: '/auth/consumer/signup/'
      path: '/auth/consumer/signup'
      fullPath: '/auth/consumer/signup'
      preLoaderRoute: typeof AuthConsumerSignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/consumer/login/': {
      id: '/auth/consumer/login/'
      path: '/auth/consumer/login'
      fullPath: '/auth/consumer/login'
      preLoaderRoute: typeof AuthConsumerLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCatalogIndexRoute: typeof DashboardCatalogIndexRoute
  DashboardChatIndexRoute: typeof DashboardChatIndexRoute
  DashboardComplaintsIndexRoute: typeof DashboardComplaintsIndexRoute
  DashboardLinksIndexRoute: typeof DashboardLinksIndexRoute
  DashboardOrdersIndexRoute: typeof DashboardOrdersIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
  DashboardSuppliersIndexRoute: typeof DashboardSuppliersIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCatalogIndexRoute: DashboardCatalogIndexRoute,
  DashboardChatIndexRoute: DashboardChatIndexRoute,
  DashboardComplaintsIndexRoute: DashboardComplaintsIndexRoute,
  DashboardLinksIndexRoute: DashboardLinksIndexRoute,
  DashboardOrdersIndexRoute: DashboardOrdersIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  DashboardSuppliersIndexRoute: DashboardSuppliersIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
  AuthConsumerLoginIndexRoute: AuthConsumerLoginIndexRoute,
  AuthConsumerSignupIndexRoute: AuthConsumerSignupIndexRoute,
  AuthSupplierLoginIndexRoute: AuthSupplierLoginIndexRoute,
  AuthSupplierSignupIndexRoute: AuthSupplierSignupIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
