/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthSupplierSignupIndexRouteImport } from './routes/auth/supplier/signup/index'
import { Route as AuthSupplierLoginIndexRouteImport } from './routes/auth/supplier/login/index'
import { Route as AuthConsumerSignupIndexRouteImport } from './routes/auth/consumer/signup/index'
import { Route as AuthConsumerLoginIndexRouteImport } from './routes/auth/consumer/login/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSupplierSignupIndexRoute = AuthSupplierSignupIndexRouteImport.update({
  id: '/auth/supplier/signup/',
  path: '/auth/supplier/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSupplierLoginIndexRoute = AuthSupplierLoginIndexRouteImport.update({
  id: '/auth/supplier/login/',
  path: '/auth/supplier/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConsumerSignupIndexRoute = AuthConsumerSignupIndexRouteImport.update({
  id: '/auth/consumer/signup/',
  path: '/auth/consumer/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConsumerLoginIndexRoute = AuthConsumerLoginIndexRouteImport.update({
  id: '/auth/consumer/login/',
  path: '/auth/consumer/login/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthIndexRoute
  '/auth/consumer/login': typeof AuthConsumerLoginIndexRoute
  '/auth/consumer/signup': typeof AuthConsumerSignupIndexRoute
  '/auth/supplier/login': typeof AuthSupplierLoginIndexRoute
  '/auth/supplier/signup': typeof AuthSupplierSignupIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthIndexRoute
  '/auth/consumer/login': typeof AuthConsumerLoginIndexRoute
  '/auth/consumer/signup': typeof AuthConsumerSignupIndexRoute
  '/auth/supplier/login': typeof AuthSupplierLoginIndexRoute
  '/auth/supplier/signup': typeof AuthSupplierSignupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/': typeof AuthIndexRoute
  '/auth/consumer/login/': typeof AuthConsumerLoginIndexRoute
  '/auth/consumer/signup/': typeof AuthConsumerSignupIndexRoute
  '/auth/supplier/login/': typeof AuthSupplierLoginIndexRoute
  '/auth/supplier/signup/': typeof AuthSupplierSignupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auth/consumer/login'
    | '/auth/consumer/signup'
    | '/auth/supplier/login'
    | '/auth/supplier/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth/consumer/login'
    | '/auth/consumer/signup'
    | '/auth/supplier/login'
    | '/auth/supplier/signup'
  id:
    | '__root__'
    | '/'
    | '/auth/'
    | '/auth/consumer/login/'
    | '/auth/consumer/signup/'
    | '/auth/supplier/login/'
    | '/auth/supplier/signup/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthConsumerLoginIndexRoute: typeof AuthConsumerLoginIndexRoute
  AuthConsumerSignupIndexRoute: typeof AuthConsumerSignupIndexRoute
  AuthSupplierLoginIndexRoute: typeof AuthSupplierLoginIndexRoute
  AuthSupplierSignupIndexRoute: typeof AuthSupplierSignupIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/supplier/signup/': {
      id: '/auth/supplier/signup/'
      path: '/auth/supplier/signup'
      fullPath: '/auth/supplier/signup'
      preLoaderRoute: typeof AuthSupplierSignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/supplier/login/': {
      id: '/auth/supplier/login/'
      path: '/auth/supplier/login'
      fullPath: '/auth/supplier/login'
      preLoaderRoute: typeof AuthSupplierLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/consumer/signup/': {
      id: '/auth/consumer/signup/'
      path: '/auth/consumer/signup'
      fullPath: '/auth/consumer/signup'
      preLoaderRoute: typeof AuthConsumerSignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/consumer/login/': {
      id: '/auth/consumer/login/'
      path: '/auth/consumer/login'
      fullPath: '/auth/consumer/login'
      preLoaderRoute: typeof AuthConsumerLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthConsumerLoginIndexRoute: AuthConsumerLoginIndexRoute,
  AuthConsumerSignupIndexRoute: AuthConsumerSignupIndexRoute,
  AuthSupplierLoginIndexRoute: AuthSupplierLoginIndexRoute,
  AuthSupplierSignupIndexRoute: AuthSupplierSignupIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
